-- vim.g.maplocalleader = "\\"
vim.g.mapleader = " "
vim.g.maplocalleader = " "
-- :ec 'SAVED'<cr>
vim.keymap.set({ 'n', 'i', 'v' }, "<C-s>", "<cmd>stopinsert | w++p<cr>", { silent = true, desc = "Save File" })
vim.keymap.set({ 'n' }, "<C-k>", ":m .-2<cr>==", { silent = true, desc = "Move line up" })
vim.keymap.set({ 'n' }, "<C-j>", ":m .+1<cr>==", { silent = true, desc = "Move line down" })
vim.keymap.set({ 'i' }, "<C-k>", "<Esc>:m .-2<cr>==a", { silent = true, desc = "Move line up" })
vim.keymap.set({ 'i' }, "<C-j>", "<Esc>:m .+1<cr>==a", { silent = true, desc = "Move line down" })
vim.keymap.set({ 'v' }, "<C-k>", ":m '<-2<cr>gv=gv", { silent = true, desc = "Move selection up" })
vim.keymap.set({ 'v' }, "<C-j>", ":m '>+1<cr>gv=gv", { silent = true, desc = "Move selection down" })
vim.keymap.set({ 'v' }, "<", "<gv", { silent = true, desc = "Indent left" })
vim.keymap.set({ 'v' }, ">", ">gv", { silent = true, desc = "Indent right" })
-- vim.keymap.set({ 'n' }, "<Tab>", ":tabn<cr>", { silent = true, desc = "Go to the next Tab Page" })
-- vim.keymap.set({ 'n' }, "<S-Tab>", ":tabp<cr>", { silent = true, desc = "Go to the previous Tab Page" })
vim.keymap.set({ 'n' }, "<C-S-o>", "<C-o>", { silent = true, desc = "Jump backwards", noremap = true })
vim.keymap.set({ 'n' }, "<Esc>", ":noh<cr>", { silent = true })
vim.keymap.set({ 'n' }, "<leader>b", "", { desc = "Buffers" })
vim.keymap.set({ 'n' }, "<leader>bd", "<cmd>bdelete<cr>", { desc = "Delete Buffer" })

-- vim.keymap.set({ 'n' }, "<leader>bn", "<cmd>bnext<cr>", { desc = "Go to the next Buffer" })
-- vim.keymap.set({ 'n' }, "<leader>bp", "<cmd>bprevious<cr>", { desc = "Go to the previous Buffer" })
vim.keymap.set({ 'n' }, "<S-Tab>", "<cmd>bnext<cr>", { desc = "Go to the next Buffer" })
vim.keymap.set({ 'n' }, "<Tab>", "<cmd>bprevious<cr>", { desc = "Go to the previous Buffer" })
vim.keymap.set({ 'n' }, "<leader>ff", ":find ", { desc = "Find file" })
vim.keymap.set({ 'i' }, "<cr>", 'pumvisible() ? "<c-y>" : "<cr>"', { expr = true, desc = "Accept Completion", })
vim.keymap.set({ 'i' }, "<Tab>", 'pumvisible() ? "<c-n>" : "<Tab>"', { expr = true, desc = "Next Completion", })
vim.keymap.set({ 'i' }, "<s-Tab>", 'pumvisible() ? "<c-p>" : "<s-Tab>"', { expr = true, desc = "Previous Completion", })
vim.keymap.set({ 'i' }, "<Esc>", 'pumvisible() ? "<Esc><Esc>" : "<Esc>"', { expr = true, desc = "Close Completion", })
vim.keymap.set({ 'i' }, "<c-l>", function() vim.snippet.jump(1) end, { desc = "Next Placeholder", })
vim.keymap.set({ 'i' }, "<c-h>", function() vim.snippet.jump(-1) end, { desc = "Previous Placeholder", })
vim.keymap.set({ 't' }, "<c-Esc>", '<c-\\><c-n>', { desc = "Exit terminal mode", })
vim.keymap.set({ "n" }, "<leader>s", "", { desc = "Show" })
vim.keymap.set({ 'n' }, "<leader>u", "", { desc = "Undo" })
